ssh_keys:
  trygvis:
    ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIJAzB6JB/hZ87M6ozsd7lgKxgOacEOZZRxa4ucs11lqq trygvis@conflatorio:
    ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIL3UZyrbXX7WMHqcZCRspkoSIfB6egrbOxXPf1zyZkAw trygvis@arius-v4:
    ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIK3NIIYprtLQFNut7GGf0va7YYFeSXKSgWDQi4qbf5Ph trygvis@biwia:
  mk:
    ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAID/YDFWYTpJtzTmVB/Be1QslYpwh4ggIFH4njeGj4gzZ marius.krabset@gmail.com:
  felix:
    ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAINgSgA8F2q/cjd9ZVC6vfACB4qsFEIoDkvr69wPZ3eId felix@kichererbse.local:
  tobiast:
    ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHb+VKD6ix0nU+8d0nNlLvyCicEn2BeOSwETUTZe/iIj tobiast@gmail.com
