all:
  hosts:
    humle:
      ansible_host: 95288538-e027-410d-bcd5-0093f678b576.pub.instances.scw.cloud
    schous:
      ansible_host: schous.vpn.scienta.cloud
      ansible_ssh_args: '-J humle.scienta.cloud'

managed:
  hosts:
    humle:
    schous:

scienta_net:
  hosts:
    humle:
    schous:
