- hosts:
    - humle
  tasks:
    - name: /etc/systemd/network/99-wg0.network
      become: yes
      notify: systemctl reload systemd-networkd
      copy:
        dest: /etc/systemd/network/99-wg0.network
        content: |
          [Match]
          Name=wg0

          [Route]
          Destination=fdb1:4242:b1ef:2002::/64
          Gateway=fdb1:4242:b1ef::1
          GatewayOnLink=yes

          [Route]
          Destination=fdb1:4242:b1ef:2003::/64
          Gateway=fdb1:4242:b1ef::1
          GatewayOnLink=yes

  handlers:
    - name: systemctl reload systemd-networkd
      become: yes
      systemd:
        service: systemd-networkd
        state: reloaded
