- hosts:
    - managed
  tasks:
    - name: apt install
      become: yes
      apt:
        name:
          - sudo

    - name: /etc/sudoers.d/99-scienta
      become: yes
      copy:
        dest: /etc/sudoers.d/99-scienta
        content: |
          # {{ ansible_managed }}
          %sudo	ALL=(ALL:ALL) NOPASSWD: ALL

    - include_role: 
        name: scienta-user
      vars:
        username: "{{ user_l.key }}"
        user: "{{ user_l.value }}"
      loop: "{{ users | dict2items }}"
      loop_control:
        loop_var: user_l
